export const BookingScreenText = {
  setDestionation: 'Set your destination   ',
  movePin: 'Drag pin to set your destination',
  planYourRide: 'Plan your Ride',
  pinLocation: 'Pin Location',
  confirmDestionation: 'Confirm Destination',
  vehicleSelection: 'Choose a Ride',
  cash: 'Cash',
  choose: 'Choose',
  confirmPickup: 'Confirm Pickup',
  pickupNow: 'Pickup Now',
  pay: 'Pay',
  rideCompleted: 'Ride completed',
  rideCompletedSubtitle: 'Please proceed to pay the fare and exit the vehicle.',
};
