export enum FONTS {
  Thin = 'Sora-Thin',
  ExtraLight = 'Sora-ExtraLight',
  Light = 'Sora-Light',
  Regular = 'Sora-Regular',
  Medium = 'Sora-Medium',
  SemiBold = 'Sora-SemiBold',
  Bold = 'Sora-Bold',
  ExtraBold = 'Sora-ExtraBold',
}

export enum Colors {
  primary = '#D7FC70',
  active = '#1054E8',
  inactive = '#666',
  lightText = '#242424',
  white = '#fff',
  black = '#000',
  lightBlack = '#141414',
  textwhite = '#FBFBFB',
  textgray = '#808080',
  grayBorder = '#1e1e1e',
  textInputPlaceholder = '#939190',
  textInputError = '#FF0000',
  textInputLabel = '#282626',
  grayBackground = '#eeeeee',
  itemSeparator = '#bcbcbc',
  otpInputBackground = '#f3f3f3',
  whereToInputBackground = '#323232',
  whereToInputLabel = '#969696',
  searchIcon = '#c3c3c3',
  searchHistoryText = '#bebebe',
  greenBackground = '#2C5F39',
}
