export const HomeScreenText = {
  whereToInputPlaceholder: 'Where to?',
  later: 'Later',
  state: 'Karnataka',
  seeAll: 'See all',
  suggestions: 'Suggestions',
  promo: 'Promo',
  homeAds: 'Enjoy 15% off on select rides',
  homeCarAdsTitle: 'Enjoy 15% off on select rides',
  homeAutoAdsTitle: 'Enjoy 15% off on select rides',
  homeCarAdsButton: 'Try Now',
  homeAutoAdsButton: 'Try Auto',
  ride: 'Ride',
  auto: 'Auto',
} as const;
